### ISSUE TITLE
Main: 콕 완료 애니메이션, 햅틱 구현

### ISSUE THREAD

**Issue by phainestha1** [Team-WeHere/WeHere#15]
## Issue
- 콕 프로세스 완료 시 애니메이션이 동작하도록 합니다.
- 콕 완료 이후 프로필 사진의 border 색상이 변경됩니다.
- 콕 이전에는 회색으로 표시된 핀이 장소의 카테고리에 해당하는 색상으로 변경됩니다.

<div>
<img width="257" alt="image" src="https://user-images.githubusercontent.com/88080251/201514224-093d28ec-fd70-4340-a4d3-39e5e82fad1e.png">

<img width="256" alt="image" src="https://user-images.githubusercontent.com/88080251/201514229-60b99eb1-e181-42f5-94d5-e13df4b30d8c.png">

<img width="105" alt="image" src="https://user-images.githubusercontent.com/88080251/201514439-2a3825f9-78fa-42f9-b142-81d56d7b976f.png">

</div>

<img width="485" alt="image" src="https://user-images.githubusercontent.com/88080251/201514481-38f71e36-8898-47a3-9393-efebdffca661.png">
(햅틱예시)

ref)
- [하트 애니메이션](https://betterprogramming.pub/floating-hearts-animation-in-swiftui-1bf2f0404b12)
- [Pulse 애니메이션](https://codepen.io/Eslam_Refa3y/pen/QWLmEMg)

## todo
- [x] 사용자의 프로필 화면에서 하트 애니메이션이 동작합니다.
- [ ] 프로필 사진의 border 색상이 변경됩니다.
- [x] 콕 완료 시 햅틱이 발생합니다.
- [x] 핀 색상이 변경됩니다.
