### ISSUE TITLE
Feature: Firebase Setting

### ISSUE THREAD

**Issue by phainestha1** [Team-WeHere/WeHere#16]
## Issue
아래 기능 구현을 위한 Firebase 세팅을 진행합니다.
- 회원가입, 로그인
- 커플 초대 / 연결
- 사용자 프로필 관리
- 콕 생성 / 저장 / 관리

## todo
- [ ] 회원가입, 로그인
- [ ] 커플 초대 / 연결
- [ ] 사용자 프로필 관리
- [ ] 콕 생성 / 저장 / 관리
