### ISSUE TITLE
Main: 검색 버튼, 검색창, 활성화 애니메이션, 검색 결과 리스트 구현

### ISSUE THREAD

**Issue by phainestha1** [Team-WeHere/WeHere#7]
## Issue
- 검색 버튼 UI를 구현합니다.
- 검색창 UI를 구현합니다.
- 검색창 활성화 애니메이션을 구현합니다.
- 검색 결과 리스트 UI를 구현합니다.

<div>
<img width="302" alt="image" src="https://user-images.githubusercontent.com/88080251/201512607-116f59fd-b3c5-42bc-9d8c-51772ee2c1c6.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/88080251/201512619-db32f673-e06e-4a8f-91c0-73ea2d148872.png">
</div>

<img width="500" alt="image" src="https://user-images.githubusercontent.com/88080251/201512628-6db293a4-c32c-4b48-a1f0-736cc9586c6e.png">

## todo
- [ ] 검색 버튼 UI를 구현합니다.
- [ ] 검색창 UI를 구현합니다.
- [ ] 검색창 활성화 애니메이션을 구현합니다.
- [ ] 검색 결과 리스트 UI를 구현합니다.
